import { ResortDataProps } from '../src/@types/resort-data.definition';

export const MockThreeDays: ResortDataProps = {
    continent: 'Europe',
    country: 'France',
    forecast: [
        {
            base: {
                feelslike_c: -10,
                feelslike_f: 15,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -5,
                temp_f: 23,
                winddir_compass: 'SW',
                winddir_deg: 224.5,
                windgst_kmh: 24,
                windgst_kts: 13,
                windgst_mph: 15,
                windgst_ms: 6.7,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.2,
                wx_code: 1,
                wx_desc: 'Partly cloudy skies',
                wx_icon: 'PartlyCloudyNight.gif',
            },
            date: '21/02/2022',
            dewpoint_c: -6,
            dewpoint_f: 22,
            frzglvl_ft: 4033,
            frzglvl_m: 1229,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 40,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'WSW',
                winddir_deg: 250.3,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kts: 10,
                windspd_mph: 11,
                windspd_ms: 5.1,
                wx_code: 1,
                wx_desc: 'Partly cloudy skies',
                wx_icon: 'PartlyCloudyNight.gif',
            },
            midcloud_pct: 0,
            precip_in: 0,
            precip_mm: 0,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.3,
            slp_mb: 1023,
            snow_in: 0,
            snow_mm: 0,
            time: '01:00',
            totalcloud_pct: 40,
            upper: {
                feelslike_c: -23,
                feelslike_f: -10,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -11,
                temp_f: 12,
                winddir_compass: 'W',
                winddir_deg: 273.4,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 51,
                windspd_kts: 27,
                windspd_mph: 32,
                windspd_ms: 14.1,
                wx_code: 1,
                wx_desc: 'Partly cloudy skies',
                wx_icon: 'PartlyCloudyNight.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
        {
            base: {
                feelslike_c: -9,
                feelslike_f: 16,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -4,
                temp_f: 24,
                winddir_compass: 'SW',
                winddir_deg: 225.8,
                windgst_kmh: 22,
                windgst_kts: 12,
                windgst_mph: 14,
                windgst_ms: 6.2,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.2,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            date: '21/02/2022',
            dewpoint_c: -5,
            dewpoint_f: 23,
            frzglvl_ft: 4413,
            frzglvl_m: 1345,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 42,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'WSW',
                winddir_deg: 240.3,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 17,
                windspd_kts: 9,
                windspd_mph: 11,
                windspd_ms: 4.8,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            midcloud_pct: 18,
            precip_in: 0.01,
            precip_mm: 0.2,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.19,
            slp_mb: 1019,
            snow_in: 0,
            snow_mm: 0,
            time: '04:00',
            totalcloud_pct: 49,
            upper: {
                feelslike_c: -26,
                feelslike_f: -15,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -12,
                temp_f: 10,
                winddir_compass: 'W',
                winddir_deg: 280.1,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 64,
                windspd_kts: 34,
                windspd_mph: 40,
                windspd_ms: 17.7,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
        // {
        //     base: {
        //         feelslike_c: -5,
        //         feelslike_f: 22,
        //         freshsnow_cm: 3.4,
        //         freshsnow_in: 1.34,
        //         temp_c: -1,
        //         temp_f: 30,
        //         winddir_compass: 'WSW',
        //         winddir_deg: 248,
        //         windgst_kmh: 15,
        //         windgst_kts: 8,
        //         windgst_mph: 9,
        //         windgst_ms: 4.2,
        //         windspd_kmh: 13,
        //         windspd_kts: 7,
        //         windspd_mph: 8,
        //         windspd_ms: 3.6,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '21/02/2022',
        //     dewpoint_c: -1,
        //     dewpoint_f: 29,
        //     frzglvl_ft: 4355,
        //     frzglvl_m: 1327,
        //     highcloud_pct: 0,
        //     hum_pct: 97,
        //     lowcloud_pct: 70,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.1,
        //         freshsnow_in: 1.61,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'W',
        //         winddir_deg: 264.3,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 22,
        //         windspd_kts: 12,
        //         windspd_mph: 14,
        //         windspd_ms: 6.2,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.13,
        //     precip_mm: 3.4,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.13,
        //     slp_mb: 1017,
        //     snow_in: 1.87,
        //     snow_mm: 47.6,
        //     time: '07:00',
        //     totalcloud_pct: 86,
        //     upper: {
        //         feelslike_c: -31,
        //         feelslike_f: -24,
        //         freshsnow_cm: 4.8,
        //         freshsnow_in: 1.87,
        //         temp_c: -16,
        //         temp_f: 4,
        //         winddir_compass: 'W',
        //         winddir_deg: 275.1,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windspd_kmh: 68,
        //         windspd_kts: 37,
        //         windspd_mph: 42,
        //         windspd_ms: 18.9,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        // {
        //     base: {
        //         feelslike_c: -4,
        //         feelslike_f: 24,
        //         freshsnow_cm: 2,
        //         freshsnow_in: 0.79,
        //         temp_c: 0,
        //         temp_f: 32,
        //         winddir_compass: 'W',
        //         winddir_deg: 272.5,
        //         windgst_kmh: 20,
        //         windgst_kts: 11,
        //         windgst_mph: 13,
        //         windgst_ms: 5.6,
        //         windspd_kmh: 17,
        //         windspd_kts: 9,
        //         windspd_mph: 10,
        //         windspd_ms: 4.6,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     date: '21/02/2022',
        //     dewpoint_c: -1,
        //     dewpoint_f: 30,
        //     frzglvl_ft: 4390,
        //     frzglvl_m: 1338,
        //     highcloud_pct: 0,
        //     hum_pct: 92,
        //     lowcloud_pct: 19,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 2.4,
        //         freshsnow_in: 0.94,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'W',
        //         winddir_deg: 273.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 23,
        //         windspd_kts: 13,
        //         windspd_mph: 15,
        //         windspd_ms: 6.5,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     midcloud_pct: 46,
        //     precip_in: 0.08,
        //     precip_mm: 2,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.08,
        //     slp_mb: 1016,
        //     snow_in: 1.1,
        //     snow_mm: 28,
        //     time: '10:00',
        //     totalcloud_pct: 35,
        //     upper: {
        //         feelslike_c: -36,
        //         feelslike_f: -33,
        //         freshsnow_cm: 2.8,
        //         freshsnow_in: 1.1,
        //         temp_c: -19,
        //         temp_f: -2,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 288.7,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 67,
        //         windspd_kts: 36,
        //         windspd_mph: 42,
        //         windspd_ms: 18.6,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -6,
        //         feelslike_f: 22,
        //         freshsnow_cm: 5.7,
        //         freshsnow_in: 2.24,
        //         temp_c: -1,
        //         temp_f: 30,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 299.5,
        //         windgst_kmh: 18,
        //         windgst_kts: 10,
        //         windgst_mph: 11,
        //         windgst_ms: 4.9,
        //         windspd_kmh: 14,
        //         windspd_kts: 7,
        //         windspd_mph: 9,
        //         windspd_ms: 3.8,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     date: '21/02/2022',
        //     dewpoint_c: -2,
        //     dewpoint_f: 28,
        //     frzglvl_ft: 3615,
        //     frzglvl_m: 1102,
        //     highcloud_pct: 0,
        //     hum_pct: 94,
        //     lowcloud_pct: 32,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 6.8,
        //         freshsnow_in: 2.69,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 302.1,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 18,
        //         windspd_kts: 10,
        //         windspd_mph: 11,
        //         windspd_ms: 5.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.22,
        //     precip_mm: 5.7,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.12,
        //     slp_mb: 1017,
        //     snow_in: 3.14,
        //     snow_mm: 79.8,
        //     time: '13:00',
        //     totalcloud_pct: 47,
        //     upper: {
        //         feelslike_c: -38,
        //         feelslike_f: -36,
        //         freshsnow_cm: 8,
        //         freshsnow_in: 3.14,
        //         temp_c: -21,
        //         temp_f: -6,
        //         winddir_compass: 'NW',
        //         winddir_deg: 306.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 58,
        //         windspd_kts: 31,
        //         windspd_mph: 36,
        //         windspd_ms: 16.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -6,
        //         feelslike_f: 21,
        //         freshsnow_cm: 3.7,
        //         freshsnow_in: 1.46,
        //         temp_c: -2,
        //         temp_f: 29,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 300,
        //         windgst_kmh: 20,
        //         windgst_kts: 11,
        //         windgst_mph: 12,
        //         windgst_ms: 5.4,
        //         windspd_kmh: 14,
        //         windspd_kts: 8,
        //         windspd_mph: 9,
        //         windspd_ms: 4,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     date: '21/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 3419,
        //     frzglvl_m: 1042,
        //     highcloud_pct: 0,
        //     hum_pct: 93,
        //     lowcloud_pct: 32,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.4,
        //         freshsnow_in: 1.75,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 303.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 21,
        //         windspd_kts: 11,
        //         windspd_mph: 13,
        //         windspd_ms: 5.8,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.15,
        //     precip_mm: 3.7,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.12,
        //     slp_mb: 1017,
        //     snow_in: 2.04,
        //     snow_mm: 51.8,
        //     time: '16:00',
        //     totalcloud_pct: 48,
        //     upper: {
        //         feelslike_c: -39,
        //         feelslike_f: -37,
        //         freshsnow_cm: 5.2,
        //         freshsnow_in: 2.04,
        //         temp_c: -21,
        //         temp_f: -6,
        //         winddir_compass: 'NW',
        //         winddir_deg: 314.9,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 65,
        //         windspd_kts: 35,
        //         windspd_mph: 40,
        //         windspd_ms: 18.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -7,
        //         feelslike_f: 19,
        //         freshsnow_cm: 4,
        //         freshsnow_in: 1.57,
        //         temp_c: -3,
        //         temp_f: 27,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 299.3,
        //         windgst_kmh: 15,
        //         windgst_kts: 8,
        //         windgst_mph: 10,
        //         windgst_ms: 4.3,
        //         windspd_kmh: 13,
        //         windspd_kts: 7,
        //         windspd_mph: 8,
        //         windspd_ms: 3.7,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '21/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 2976,
        //     frzglvl_m: 907,
        //     highcloud_pct: 0,
        //     hum_pct: 98,
        //     lowcloud_pct: 70,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.8,
        //         freshsnow_in: 1.89,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'NW',
        //         winddir_deg: 306.7,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 24,
        //         windspd_kts: 13,
        //         windspd_mph: 15,
        //         windspd_ms: 6.8,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 52,
        //     precip_in: 0.16,
        //     precip_mm: 4,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.15,
        //     slp_mb: 1018,
        //     snow_in: 2.2,
        //     snow_mm: 56,
        //     time: '19:00',
        //     totalcloud_pct: 88,
        //     upper: {
        //         feelslike_c: -39,
        //         feelslike_f: -39,
        //         freshsnow_cm: 5.6,
        //         freshsnow_in: 2.2,
        //         temp_c: -21,
        //         temp_f: -5,
        //         winddir_compass: 'NW',
        //         winddir_deg: 322.3,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 81,
        //         windspd_kts: 44,
        //         windspd_mph: 50,
        //         windspd_ms: 22.5,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        // {
        //     base: {
        //         feelslike_c: -7,
        //         feelslike_f: 20,
        //         freshsnow_cm: 3.8,
        //         freshsnow_in: 1.5,
        //         temp_c: -3,
        //         temp_f: 27,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 303.9,
        //         windgst_kmh: 14,
        //         windgst_kts: 7,
        //         windgst_mph: 9,
        //         windgst_ms: 3.8,
        //         windspd_kmh: 12,
        //         windspd_kts: 6,
        //         windspd_mph: 7,
        //         windspd_ms: 3.3,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '21/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 2996,
        //     frzglvl_m: 913,
        //     highcloud_pct: 0,
        //     hum_pct: 97,
        //     lowcloud_pct: 69,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.6,
        //         freshsnow_in: 1.8,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'NW',
        //         winddir_deg: 316.5,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 23,
        //         windspd_kts: 12,
        //         windspd_mph: 14,
        //         windspd_ms: 6.3,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 48,
        //     precip_in: 0.15,
        //     precip_mm: 3.8,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.24,
        //     slp_mb: 1021,
        //     snow_in: 2.09,
        //     snow_mm: 53.2,
        //     time: '22:00',
        //     totalcloud_pct: 85,
        //     upper: {
        //         feelslike_c: -37,
        //         feelslike_f: -35,
        //         freshsnow_cm: 5.3,
        //         freshsnow_in: 2.09,
        //         temp_c: -20,
        //         temp_f: -5,
        //         winddir_compass: 'NNW',
        //         winddir_deg: 337.6,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 60,
        //         windspd_kts: 33,
        //         windspd_mph: 38,
        //         windspd_ms: 16.8,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        {
            base: {
                feelslike_c: -10,
                feelslike_f: 15,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -5,
                temp_f: 23,
                winddir_compass: 'SW',
                winddir_deg: 224.5,
                windgst_kmh: 24,
                windgst_kts: 13,
                windgst_mph: 15,
                windgst_ms: 6.7,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.2,
                wx_code: 1,
                wx_desc: 'Partly cloudy skies',
                wx_icon: 'PartlyCloudyNight.gif',
            },
            date: '22/02/2022',
            dewpoint_c: -6,
            dewpoint_f: 22,
            frzglvl_ft: 4033,
            frzglvl_m: 1229,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 40,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'WSW',
                winddir_deg: 250.3,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kts: 10,
                windspd_mph: 11,
                windspd_ms: 5.1,
                wx_code: 1,
                wx_desc: 'Partly cloudy skies',
                wx_icon: 'PartlyCloudyNight.gif',
            },
            midcloud_pct: 0,
            precip_in: 0,
            precip_mm: 0,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.3,
            slp_mb: 1023,
            snow_in: 0,
            snow_mm: 0,
            time: '01:00',
            totalcloud_pct: 40,
            upper: {
                feelslike_c: -23,
                feelslike_f: -10,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -11,
                temp_f: 12,
                winddir_compass: 'W',
                winddir_deg: 273.4,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 51,
                windspd_kts: 27,
                windspd_mph: 32,
                windspd_ms: 14.1,
                wx_code: 1,
                wx_desc: 'Partly cloudy skies',
                wx_icon: 'PartlyCloudyNight.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
        {
            base: {
                feelslike_c: -9,
                feelslike_f: 16,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -4,
                temp_f: 24,
                winddir_compass: 'SW',
                winddir_deg: 225.8,
                windgst_kmh: 22,
                windgst_kts: 12,
                windgst_mph: 14,
                windgst_ms: 6.2,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.2,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            date: '22/02/2022',
            dewpoint_c: -5,
            dewpoint_f: 23,
            frzglvl_ft: 4413,
            frzglvl_m: 1345,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 42,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'WSW',
                winddir_deg: 240.3,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 17,
                windspd_kts: 9,
                windspd_mph: 11,
                windspd_ms: 4.8,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            midcloud_pct: 18,
            precip_in: 0.01,
            precip_mm: 0.2,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.19,
            slp_mb: 1019,
            snow_in: 0,
            snow_mm: 0,
            time: '04:00',
            totalcloud_pct: 49,
            upper: {
                feelslike_c: -26,
                feelslike_f: -15,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -12,
                temp_f: 10,
                winddir_compass: 'W',
                winddir_deg: 280.1,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 64,
                windspd_kts: 34,
                windspd_mph: 40,
                windspd_ms: 17.7,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
        // {
        //     base: {
        //         feelslike_c: -5,
        //         feelslike_f: 22,
        //         freshsnow_cm: 3.4,
        //         freshsnow_in: 1.34,
        //         temp_c: -1,
        //         temp_f: 30,
        //         winddir_compass: 'WSW',
        //         winddir_deg: 248,
        //         windgst_kmh: 15,
        //         windgst_kts: 8,
        //         windgst_mph: 9,
        //         windgst_ms: 4.2,
        //         windspd_kmh: 13,
        //         windspd_kts: 7,
        //         windspd_mph: 8,
        //         windspd_ms: 3.6,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '22/02/2022',
        //     dewpoint_c: -1,
        //     dewpoint_f: 29,
        //     frzglvl_ft: 4355,
        //     frzglvl_m: 1327,
        //     highcloud_pct: 0,
        //     hum_pct: 97,
        //     lowcloud_pct: 70,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.1,
        //         freshsnow_in: 1.61,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'W',
        //         winddir_deg: 264.3,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 22,
        //         windspd_kts: 12,
        //         windspd_mph: 14,
        //         windspd_ms: 6.2,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.13,
        //     precip_mm: 3.4,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.13,
        //     slp_mb: 1017,
        //     snow_in: 1.87,
        //     snow_mm: 47.6,
        //     time: '07:00',
        //     totalcloud_pct: 86,
        //     upper: {
        //         feelslike_c: -31,
        //         feelslike_f: -24,
        //         freshsnow_cm: 4.8,
        //         freshsnow_in: 1.87,
        //         temp_c: -16,
        //         temp_f: 4,
        //         winddir_compass: 'W',
        //         winddir_deg: 275.1,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windspd_kmh: 68,
        //         windspd_kts: 37,
        //         windspd_mph: 42,
        //         windspd_ms: 18.9,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        // {
        //     base: {
        //         feelslike_c: -4,
        //         feelslike_f: 24,
        //         freshsnow_cm: 2,
        //         freshsnow_in: 0.79,
        //         temp_c: 0,
        //         temp_f: 32,
        //         winddir_compass: 'W',
        //         winddir_deg: 272.5,
        //         windgst_kmh: 20,
        //         windgst_kts: 11,
        //         windgst_mph: 13,
        //         windgst_ms: 5.6,
        //         windspd_kmh: 17,
        //         windspd_kts: 9,
        //         windspd_mph: 10,
        //         windspd_ms: 4.6,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     date: '22/02/2022',
        //     dewpoint_c: -1,
        //     dewpoint_f: 30,
        //     frzglvl_ft: 4390,
        //     frzglvl_m: 1338,
        //     highcloud_pct: 0,
        //     hum_pct: 92,
        //     lowcloud_pct: 19,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 2.4,
        //         freshsnow_in: 0.94,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'W',
        //         winddir_deg: 273.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 23,
        //         windspd_kts: 13,
        //         windspd_mph: 15,
        //         windspd_ms: 6.5,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     midcloud_pct: 46,
        //     precip_in: 0.08,
        //     precip_mm: 2,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.08,
        //     slp_mb: 1016,
        //     snow_in: 1.1,
        //     snow_mm: 28,
        //     time: '10:00',
        //     totalcloud_pct: 35,
        //     upper: {
        //         feelslike_c: -36,
        //         feelslike_f: -33,
        //         freshsnow_cm: 2.8,
        //         freshsnow_in: 1.1,
        //         temp_c: -19,
        //         temp_f: -2,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 288.7,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 67,
        //         windspd_kts: 36,
        //         windspd_mph: 42,
        //         windspd_ms: 18.6,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -6,
        //         feelslike_f: 22,
        //         freshsnow_cm: 5.7,
        //         freshsnow_in: 2.24,
        //         temp_c: -1,
        //         temp_f: 30,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 299.5,
        //         windgst_kmh: 18,
        //         windgst_kts: 10,
        //         windgst_mph: 11,
        //         windgst_ms: 4.9,
        //         windspd_kmh: 14,
        //         windspd_kts: 7,
        //         windspd_mph: 9,
        //         windspd_ms: 3.8,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     date: '22/02/2022',
        //     dewpoint_c: -2,
        //     dewpoint_f: 28,
        //     frzglvl_ft: 3615,
        //     frzglvl_m: 1102,
        //     highcloud_pct: 0,
        //     hum_pct: 94,
        //     lowcloud_pct: 32,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 6.8,
        //         freshsnow_in: 2.69,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 302.1,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 18,
        //         windspd_kts: 10,
        //         windspd_mph: 11,
        //         windspd_ms: 5.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.22,
        //     precip_mm: 5.7,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.12,
        //     slp_mb: 1017,
        //     snow_in: 3.14,
        //     snow_mm: 79.8,
        //     time: '13:00',
        //     totalcloud_pct: 47,
        //     upper: {
        //         feelslike_c: -38,
        //         feelslike_f: -36,
        //         freshsnow_cm: 8,
        //         freshsnow_in: 3.14,
        //         temp_c: -21,
        //         temp_f: -6,
        //         winddir_compass: 'NW',
        //         winddir_deg: 306.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 58,
        //         windspd_kts: 31,
        //         windspd_mph: 36,
        //         windspd_ms: 16.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -6,
        //         feelslike_f: 21,
        //         freshsnow_cm: 3.7,
        //         freshsnow_in: 1.46,
        //         temp_c: -2,
        //         temp_f: 29,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 300,
        //         windgst_kmh: 20,
        //         windgst_kts: 11,
        //         windgst_mph: 12,
        //         windgst_ms: 5.4,
        //         windspd_kmh: 14,
        //         windspd_kts: 8,
        //         windspd_mph: 9,
        //         windspd_ms: 4,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     date: '22/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 3419,
        //     frzglvl_m: 1042,
        //     highcloud_pct: 0,
        //     hum_pct: 93,
        //     lowcloud_pct: 32,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.4,
        //         freshsnow_in: 1.75,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 303.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 21,
        //         windspd_kts: 11,
        //         windspd_mph: 13,
        //         windspd_ms: 5.8,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.15,
        //     precip_mm: 3.7,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.12,
        //     slp_mb: 1017,
        //     snow_in: 2.04,
        //     snow_mm: 51.8,
        //     time: '16:00',
        //     totalcloud_pct: 48,
        //     upper: {
        //         feelslike_c: -39,
        //         feelslike_f: -37,
        //         freshsnow_cm: 5.2,
        //         freshsnow_in: 2.04,
        //         temp_c: -21,
        //         temp_f: -6,
        //         winddir_compass: 'NW',
        //         winddir_deg: 314.9,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 65,
        //         windspd_kts: 35,
        //         windspd_mph: 40,
        //         windspd_ms: 18.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -7,
        //         feelslike_f: 19,
        //         freshsnow_cm: 4,
        //         freshsnow_in: 1.57,
        //         temp_c: -3,
        //         temp_f: 27,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 299.3,
        //         windgst_kmh: 15,
        //         windgst_kts: 8,
        //         windgst_mph: 10,
        //         windgst_ms: 4.3,
        //         windspd_kmh: 13,
        //         windspd_kts: 7,
        //         windspd_mph: 8,
        //         windspd_ms: 3.7,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '22/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 2976,
        //     frzglvl_m: 907,
        //     highcloud_pct: 0,
        //     hum_pct: 98,
        //     lowcloud_pct: 70,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.8,
        //         freshsnow_in: 1.89,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'NW',
        //         winddir_deg: 306.7,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 24,
        //         windspd_kts: 13,
        //         windspd_mph: 15,
        //         windspd_ms: 6.8,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 52,
        //     precip_in: 0.16,
        //     precip_mm: 4,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.15,
        //     slp_mb: 1018,
        //     snow_in: 2.2,
        //     snow_mm: 56,
        //     time: '19:00',
        //     totalcloud_pct: 88,
        //     upper: {
        //         feelslike_c: -39,
        //         feelslike_f: -39,
        //         freshsnow_cm: 5.6,
        //         freshsnow_in: 2.2,
        //         temp_c: -21,
        //         temp_f: -5,
        //         winddir_compass: 'NW',
        //         winddir_deg: 322.3,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 81,
        //         windspd_kts: 44,
        //         windspd_mph: 50,
        //         windspd_ms: 22.5,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        // {
        //     base: {
        //         feelslike_c: -7,
        //         feelslike_f: 20,
        //         freshsnow_cm: 3.8,
        //         freshsnow_in: 1.5,
        //         temp_c: -3,
        //         temp_f: 27,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 303.9,
        //         windgst_kmh: 14,
        //         windgst_kts: 7,
        //         windgst_mph: 9,
        //         windgst_ms: 3.8,
        //         windspd_kmh: 12,
        //         windspd_kts: 6,
        //         windspd_mph: 7,
        //         windspd_ms: 3.3,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '22/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 2996,
        //     frzglvl_m: 913,
        //     highcloud_pct: 0,
        //     hum_pct: 97,
        //     lowcloud_pct: 69,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.6,
        //         freshsnow_in: 1.8,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'NW',
        //         winddir_deg: 316.5,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 23,
        //         windspd_kts: 12,
        //         windspd_mph: 14,
        //         windspd_ms: 6.3,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 48,
        //     precip_in: 0.15,
        //     precip_mm: 3.8,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.24,
        //     slp_mb: 1021,
        //     snow_in: 2.09,
        //     snow_mm: 53.2,
        //     time: '22:00',
        //     totalcloud_pct: 85,
        //     upper: {
        //         feelslike_c: -37,
        //         feelslike_f: -35,
        //         freshsnow_cm: 5.3,
        //         freshsnow_in: 2.09,
        //         temp_c: -20,
        //         temp_f: -5,
        //         winddir_compass: 'NNW',
        //         winddir_deg: 337.6,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 60,
        //         windspd_kts: 33,
        //         windspd_mph: 38,
        //         windspd_ms: 16.8,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        {
            base: {
                feelslike_c: -7,
                feelslike_f: 20,
                freshsnow_cm: 3.8,
                freshsnow_in: 1.5,
                temp_c: -3,
                temp_f: 27,
                winddir_compass: 'WNW',
                winddir_deg: 303.9,
                windgst_kmh: 14,
                windgst_kts: 7,
                windgst_mph: 9,
                windgst_ms: 3.8,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.3,
                wx_code: 75,
                wx_desc: 'Heavy snow',
                wx_icon: 'HeavySnow.gif',
            },
            date: '23/02/2022',
            dewpoint_c: -6,
            dewpoint_f: 22,
            frzglvl_ft: 4033,
            frzglvl_m: 1229,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 40,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 4.6,
                freshsnow_in: 1.8,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'NW',
                winddir_deg: 316.5,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 23,
                windspd_kts: 12,
                windspd_mph: 14,
                windspd_ms: 6.3,
                wx_code: 75,
                wx_desc: 'Heavy snow',
                wx_icon: 'HeavySnow.gif',
            },
            midcloud_pct: 0,
            precip_in: 0,
            precip_mm: 0,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.3,
            slp_mb: 1023,
            snow_in: 0,
            snow_mm: 0,
            time: '01:00',
            totalcloud_pct: 40,
            upper: {
                feelslike_c: -37,
                feelslike_f: -35,
                freshsnow_cm: 5.3,
                freshsnow_in: 2.09,
                temp_c: -20,
                temp_f: -5,
                winddir_compass: 'NNW',
                winddir_deg: 337.6,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 60,
                windspd_kts: 33,
                windspd_mph: 38,
                windspd_ms: 16.8,
                wx_code: 75,
                wx_desc: 'Heavy snow',
                wx_icon: 'HeavySnow.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
        {
            base: {
                feelslike_c: -9,
                feelslike_f: 16,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -4,
                temp_f: 24,
                winddir_compass: 'SW',
                winddir_deg: 225.8,
                windgst_kmh: 22,
                windgst_kts: 12,
                windgst_mph: 14,
                windgst_ms: 6.2,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.2,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            date: '23/02/2022',
            dewpoint_c: -5,
            dewpoint_f: 23,
            frzglvl_ft: 4413,
            frzglvl_m: 1345,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 42,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'WSW',
                winddir_deg: 240.3,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 17,
                windspd_kts: 9,
                windspd_mph: 11,
                windspd_ms: 4.8,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            midcloud_pct: 18,
            precip_in: 0.01,
            precip_mm: 0.2,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.19,
            slp_mb: 1019,
            snow_in: 0,
            snow_mm: 0,
            time: '04:00',
            totalcloud_pct: 49,
            upper: {
                feelslike_c: -26,
                feelslike_f: -15,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -12,
                temp_f: 10,
                winddir_compass: 'W',
                winddir_deg: 280.1,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 64,
                windspd_kts: 34,
                windspd_mph: 40,
                windspd_ms: 17.7,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
        // {
        //     base: {
        //         feelslike_c: -5,
        //         feelslike_f: 22,
        //         freshsnow_cm: 3.4,
        //         freshsnow_in: 1.34,
        //         temp_c: -1,
        //         temp_f: 30,
        //         winddir_compass: 'WSW',
        //         winddir_deg: 248,
        //         windgst_kmh: 15,
        //         windgst_kts: 8,
        //         windgst_mph: 9,
        //         windgst_ms: 4.2,
        //         windspd_kmh: 13,
        //         windspd_kts: 7,
        //         windspd_mph: 8,
        //         windspd_ms: 3.6,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '23/02/2022',
        //     dewpoint_c: -1,
        //     dewpoint_f: 29,
        //     frzglvl_ft: 4355,
        //     frzglvl_m: 1327,
        //     highcloud_pct: 0,
        //     hum_pct: 97,
        //     lowcloud_pct: 70,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.1,
        //         freshsnow_in: 1.61,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'W',
        //         winddir_deg: 264.3,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 22,
        //         windspd_kts: 12,
        //         windspd_mph: 14,
        //         windspd_ms: 6.2,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.13,
        //     precip_mm: 3.4,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.13,
        //     slp_mb: 1017,
        //     snow_in: 1.87,
        //     snow_mm: 47.6,
        //     time: '07:00',
        //     totalcloud_pct: 86,
        //     upper: {
        //         feelslike_c: -31,
        //         feelslike_f: -24,
        //         freshsnow_cm: 4.8,
        //         freshsnow_in: 1.87,
        //         temp_c: -16,
        //         temp_f: 4,
        //         winddir_compass: 'W',
        //         winddir_deg: 275.1,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windspd_kmh: 68,
        //         windspd_kts: 37,
        //         windspd_mph: 42,
        //         windspd_ms: 18.9,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        // {
        //     base: {
        //         feelslike_c: -4,
        //         feelslike_f: 24,
        //         freshsnow_cm: 2,
        //         freshsnow_in: 0.79,
        //         temp_c: 0,
        //         temp_f: 32,
        //         winddir_compass: 'W',
        //         winddir_deg: 272.5,
        //         windgst_kmh: 20,
        //         windgst_kts: 11,
        //         windgst_mph: 13,
        //         windgst_ms: 5.6,
        //         windspd_kmh: 17,
        //         windspd_kts: 9,
        //         windspd_mph: 10,
        //         windspd_ms: 4.6,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     date: '23/02/2022',
        //     dewpoint_c: -1,
        //     dewpoint_f: 30,
        //     frzglvl_ft: 4390,
        //     frzglvl_m: 1338,
        //     highcloud_pct: 0,
        //     hum_pct: 92,
        //     lowcloud_pct: 19,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 2.4,
        //         freshsnow_in: 0.94,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'W',
        //         winddir_deg: 273.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 23,
        //         windspd_kts: 13,
        //         windspd_mph: 15,
        //         windspd_ms: 6.5,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     midcloud_pct: 46,
        //     precip_in: 0.08,
        //     precip_mm: 2,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.08,
        //     slp_mb: 1016,
        //     snow_in: 1.1,
        //     snow_mm: 28,
        //     time: '10:00',
        //     totalcloud_pct: 35,
        //     upper: {
        //         feelslike_c: -36,
        //         feelslike_f: -33,
        //         freshsnow_cm: 2.8,
        //         freshsnow_in: 1.1,
        //         temp_c: -19,
        //         temp_f: -2,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 288.7,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 67,
        //         windspd_kts: 36,
        //         windspd_mph: 42,
        //         windspd_ms: 18.6,
        //         wx_code: 94,
        //         wx_desc: 'Moderate or heavy snow with thunder',
        //         wx_icon: 'CloudSleetSnowThunder.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -6,
        //         feelslike_f: 22,
        //         freshsnow_cm: 5.7,
        //         freshsnow_in: 2.24,
        //         temp_c: -1,
        //         temp_f: 30,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 299.5,
        //         windgst_kmh: 18,
        //         windgst_kts: 10,
        //         windgst_mph: 11,
        //         windgst_ms: 4.9,
        //         windspd_kmh: 14,
        //         windspd_kts: 7,
        //         windspd_mph: 9,
        //         windspd_ms: 3.8,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     date: '23/02/2022',
        //     dewpoint_c: -2,
        //     dewpoint_f: 28,
        //     frzglvl_ft: 3615,
        //     frzglvl_m: 1102,
        //     highcloud_pct: 0,
        //     hum_pct: 94,
        //     lowcloud_pct: 32,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 6.8,
        //         freshsnow_in: 2.69,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 302.1,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 18,
        //         windspd_kts: 10,
        //         windspd_mph: 11,
        //         windspd_ms: 5.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.22,
        //     precip_mm: 5.7,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.12,
        //     slp_mb: 1017,
        //     snow_in: 3.14,
        //     snow_mm: 79.8,
        //     time: '13:00',
        //     totalcloud_pct: 47,
        //     upper: {
        //         feelslike_c: -38,
        //         feelslike_f: -36,
        //         freshsnow_cm: 8,
        //         freshsnow_in: 3.14,
        //         temp_c: -21,
        //         temp_f: -6,
        //         winddir_compass: 'NW',
        //         winddir_deg: 306.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 58,
        //         windspd_kts: 31,
        //         windspd_mph: 36,
        //         windspd_ms: 16.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -6,
        //         feelslike_f: 21,
        //         freshsnow_cm: 3.7,
        //         freshsnow_in: 1.46,
        //         temp_c: -2,
        //         temp_f: 29,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 300,
        //         windgst_kmh: 20,
        //         windgst_kts: 11,
        //         windgst_mph: 12,
        //         windgst_ms: 5.4,
        //         windspd_kmh: 14,
        //         windspd_kts: 8,
        //         windspd_mph: 9,
        //         windspd_ms: 4,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     date: '23/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 3419,
        //     frzglvl_m: 1042,
        //     highcloud_pct: 0,
        //     hum_pct: 93,
        //     lowcloud_pct: 32,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.4,
        //         freshsnow_in: 1.75,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 303.8,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 21,
        //         windspd_kts: 11,
        //         windspd_mph: 13,
        //         windspd_ms: 5.8,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     midcloud_pct: 44,
        //     precip_in: 0.15,
        //     precip_mm: 3.7,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.12,
        //     slp_mb: 1017,
        //     snow_in: 2.04,
        //     snow_mm: 51.8,
        //     time: '16:00',
        //     totalcloud_pct: 48,
        //     upper: {
        //         feelslike_c: -39,
        //         feelslike_f: -37,
        //         freshsnow_cm: 5.2,
        //         freshsnow_in: 2.04,
        //         temp_c: -21,
        //         temp_f: -6,
        //         winddir_compass: 'NW',
        //         winddir_deg: 314.9,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 65,
        //         windspd_kts: 35,
        //         windspd_mph: 40,
        //         windspd_ms: 18.1,
        //         wx_code: 74,
        //         wx_desc: 'Patchy heavy snow',
        //         wx_icon: 'HeavySnowSwrsDay.gif',
        //     },
        //     vis_km: 5,
        //     vis_mi: 3,
        // },
        // {
        //     base: {
        //         feelslike_c: -7,
        //         feelslike_f: 19,
        //         freshsnow_cm: 4,
        //         freshsnow_in: 1.57,
        //         temp_c: -3,
        //         temp_f: 27,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 299.3,
        //         windgst_kmh: 15,
        //         windgst_kts: 8,
        //         windgst_mph: 10,
        //         windgst_ms: 4.3,
        //         windspd_kmh: 13,
        //         windspd_kts: 7,
        //         windspd_mph: 8,
        //         windspd_ms: 3.7,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '23/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 2976,
        //     frzglvl_m: 907,
        //     highcloud_pct: 0,
        //     hum_pct: 98,
        //     lowcloud_pct: 70,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.8,
        //         freshsnow_in: 1.89,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'NW',
        //         winddir_deg: 306.7,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 24,
        //         windspd_kts: 13,
        //         windspd_mph: 15,
        //         windspd_ms: 6.8,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 52,
        //     precip_in: 0.16,
        //     precip_mm: 4,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.15,
        //     slp_mb: 1018,
        //     snow_in: 2.2,
        //     snow_mm: 56,
        //     time: '19:00',
        //     totalcloud_pct: 88,
        //     upper: {
        //         feelslike_c: -39,
        //         feelslike_f: -39,
        //         freshsnow_cm: 5.6,
        //         freshsnow_in: 2.2,
        //         temp_c: -21,
        //         temp_f: -5,
        //         winddir_compass: 'NW',
        //         winddir_deg: 322.3,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 81,
        //         windspd_kts: 44,
        //         windspd_mph: 50,
        //         windspd_ms: 22.5,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        // {
        //     base: {
        //         feelslike_c: -7,
        //         feelslike_f: 20,
        //         freshsnow_cm: 3.8,
        //         freshsnow_in: 1.5,
        //         temp_c: -3,
        //         temp_f: 27,
        //         winddir_compass: 'WNW',
        //         winddir_deg: 303.9,
        //         windgst_kmh: 14,
        //         windgst_kts: 7,
        //         windgst_mph: 9,
        //         windgst_ms: 3.8,
        //         windspd_kmh: 12,
        //         windspd_kts: 6,
        //         windspd_mph: 7,
        //         windspd_ms: 3.3,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     date: '23/02/2022',
        //     dewpoint_c: -3,
        //     dewpoint_f: 27,
        //     frzglvl_ft: 2996,
        //     frzglvl_m: 913,
        //     highcloud_pct: 0,
        //     hum_pct: 97,
        //     lowcloud_pct: 69,
        //     mid: {
        //         feelslike_c: null,
        //         feelslike_f: null,
        //         freshsnow_cm: 4.6,
        //         freshsnow_in: 1.8,
        //         temp_c: null,
        //         temp_f: null,
        //         winddir_compass: 'NW',
        //         winddir_deg: 316.5,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 23,
        //         windspd_kts: 12,
        //         windspd_mph: 14,
        //         windspd_ms: 6.3,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     midcloud_pct: 48,
        //     precip_in: 0.15,
        //     precip_mm: 3.8,
        //     rain_in: 0,
        //     rain_mm: 0,
        //     slp_in: 30.24,
        //     slp_mb: 1021,
        //     snow_in: 2.09,
        //     snow_mm: 53.2,
        //     time: '22:00',
        //     totalcloud_pct: 85,
        //     upper: {
        //         feelslike_c: -37,
        //         feelslike_f: -35,
        //         freshsnow_cm: 5.3,
        //         freshsnow_in: 2.09,
        //         temp_c: -20,
        //         temp_f: -5,
        //         winddir_compass: 'NNW',
        //         winddir_deg: 337.6,
        //         windgst_kmh: null,
        //         windgst_kts: null,
        //         windgst_mph: null,
        //         windgst_ms: null,
        //         windspd_kmh: 60,
        //         windspd_kts: 33,
        //         windspd_mph: 38,
        //         windspd_ms: 16.8,
        //         wx_code: 75,
        //         wx_desc: 'Heavy snow',
        //         wx_icon: 'HeavySnow.gif',
        //     },
        //     vis_km: 2,
        //     vis_mi: 1,
        // },
        {
            base: {
                feelslike_c: -7,
                feelslike_f: 20,
                freshsnow_cm: 3.8,
                freshsnow_in: 1.5,
                temp_c: -3,
                temp_f: 27,
                winddir_compass: 'WNW',
                winddir_deg: 303.9,
                windgst_kmh: 14,
                windgst_kts: 7,
                windgst_mph: 9,
                windgst_ms: 3.8,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.3,
                wx_code: 75,
                wx_desc: 'Heavy snow',
                wx_icon: 'HeavySnow.gif',
            },
            date: '24/02/2022',
            dewpoint_c: -6,
            dewpoint_f: 22,
            frzglvl_ft: 4033,
            frzglvl_m: 1229,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 40,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 4.6,
                freshsnow_in: 1.8,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'NW',
                winddir_deg: 316.5,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 23,
                windspd_kts: 12,
                windspd_mph: 14,
                windspd_ms: 6.3,
                wx_code: 75,
                wx_desc: 'Heavy snow',
                wx_icon: 'HeavySnow.gif',
            },
            midcloud_pct: 0,
            precip_in: 0,
            precip_mm: 0,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.3,
            slp_mb: 1023,
            snow_in: 0,
            snow_mm: 0,
            time: '01:00',
            totalcloud_pct: 40,
            upper: {
                feelslike_c: -37,
                feelslike_f: -35,
                freshsnow_cm: 5.3,
                freshsnow_in: 2.09,
                temp_c: -20,
                temp_f: -5,
                winddir_compass: 'NNW',
                winddir_deg: 337.6,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 60,
                windspd_kts: 33,
                windspd_mph: 38,
                windspd_ms: 16.8,
                wx_code: 75,
                wx_desc: 'Heavy snow',
                wx_icon: 'HeavySnow.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
        {
            base: {
                feelslike_c: -9,
                feelslike_f: 16,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -4,
                temp_f: 24,
                winddir_compass: 'SW',
                winddir_deg: 225.8,
                windgst_kmh: 22,
                windgst_kts: 12,
                windgst_mph: 14,
                windgst_ms: 6.2,
                windspd_kmh: 12,
                windspd_kts: 6,
                windspd_mph: 7,
                windspd_ms: 3.2,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            date: '24/02/2022',
            dewpoint_c: -5,
            dewpoint_f: 23,
            frzglvl_ft: 4413,
            frzglvl_m: 1345,
            highcloud_pct: 0,
            hum_pct: 94,
            lowcloud_pct: 42,
            mid: {
                feelslike_c: null,
                feelslike_f: null,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                winddir_compass: 'WSW',
                winddir_deg: 240.3,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 17,
                windspd_kts: 9,
                windspd_mph: 11,
                windspd_ms: 4.8,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            midcloud_pct: 18,
            precip_in: 0.01,
            precip_mm: 0.2,
            rain_in: 0,
            rain_mm: 0,
            slp_in: 30.19,
            slp_mb: 1019,
            snow_in: 0,
            snow_mm: 0,
            time: '04:00',
            totalcloud_pct: 49,
            upper: {
                feelslike_c: -26,
                feelslike_f: -15,
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: -12,
                temp_f: 10,
                winddir_compass: 'W',
                winddir_deg: 280.1,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_mph: null,
                windgst_ms: null,
                windspd_kmh: 64,
                windspd_kts: 34,
                windspd_mph: 40,
                windspd_ms: 17.7,
                wx_code: 70,
                wx_desc: 'Patchy light snow',
                wx_icon: 'OccLightSnow.gif',
            },
            vis_km: 10,
            vis_mi: 6,
        },
    ],
    id: 333003,
    name: 'Chamonix',
};
