import { WeatherTypes } from '../../../../@types/resort-data.definition';
import { ResortButtonDataProps, ResortDataCardProps } from './resort-data-card.definition';

export const ForecastDataCardData: ResortDataCardProps = {
    weatherConfig: {
        weatherConfig: {
            date: '24/09/2015',
            time: '01:00',
            lowcloud_pct: 17,
            midcloud_pct: 0,
            highcloud_pct: 0,
            totalcloud_pct: 17,
            frzglvl_ft: 10071,
            frzglvl_m: 3070,
            precip_mm: 0,
            precip_in: 0,
            rain_mm: 7,
            rain_in: 0,
            snow_mm: 2,
            snow_in: 0,
            hum_pct: 89,
            dewpoint_c: -2,
            dewpoint_f: 29,
            vis_km: 10,
            vis_mi: 6,
            slp_mb: 1020,
            slp_in: 30.21,
            base: {
                wx_desc: 'Clear skies',
                wx_code: 0,
                wx_icon: 'Clear.gif',
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: 30,
                temp_f: null,
                feelslike_c: 32,
                feelslike_f: null,
                winddir_deg: 5.9,
                winddir_compass: 'N',
                windspd_mph: 5,
                windspd_kmh: 8,
                windspd_kts: 4,
                windspd_ms: 2.3,
                windgst_mph: 11,
                windgst_kmh: 17,
                windgst_kts: 9,
                windgst_ms: 4.8,
            },
            mid: {
                wx_desc: 'Clear skies',
                wx_code: 0,
                wx_icon: 'Clear.gif',
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                feelslike_c: null,
                feelslike_f: null,
                winddir_deg: 357.8,
                winddir_compass: 'N',
                windspd_mph: 9,
                windspd_kmh: 15,
                windspd_kts: 8,
                windspd_ms: 4.1,
                windgst_mph: null,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_ms: null,
            },
            upper: {
                wx_desc: 'Clear skies',
                wx_code: 0,
                wx_icon: 'Clear.gif',
                freshsnow_cm: 0,
                freshsnow_in: 0,
                temp_c: null,
                temp_f: null,
                feelslike_c: null,
                feelslike_f: null,
                winddir_deg: 340.9,
                winddir_compass: 'NNW',
                windspd_mph: 13,
                windspd_kmh: 21,
                windspd_kts: 11,
                windspd_ms: 5.8,
                windgst_mph: null,
                windgst_kmh: null,
                windgst_kts: null,
                windgst_ms: null,
            },
        },
        weatherGroup: WeatherTypes.GENERAL,
    },
};

export const buttonData = {
    [WeatherTypes.GENERAL]: [
        {
            icon: 'temp',
            title: 'Temp:',
            key: 'temp',
        },
        {
            icon: 'tempEmpty',
            title: 'Feels Like:',
            key: 'feelsLike',
        },
        {
            icon: 'freezing',
            title: 'Freeze Lvl:',
            key: 'frzglvl_m',
        },
        {
            icon: 'humidity',
            title: 'Humidity %:',
            key: 'hum_pct',
        },
        {
            icon: 'eye',
            title: 'Vis:',
            key: 'visibility',
        },
    ],
    [WeatherTypes.CLOUD]: [
        {
            icon: 'cloudy',
            title: 'Total %:',
            key: 'totalcloud_pct',
        },
        {
            icon: 'cloudLow',
            title: 'Low %:',
            key: 'lowcloud_pct',
        },
        {
            icon: 'cloud',
            title: 'Mid %:',
            key: 'midcloud_pct',
        },
        {
            icon: 'cloudHigh',
            title: 'High %:',
            key: 'highcloud_pct',
        },
    ],
    [WeatherTypes.RAIN]: [
        {
            icon: 'rainDrop',
            title: 'Total mm:',
            key: 'precip_mm',
        },
        {
            icon: 'rain',
            title: 'Rain mm:',
            key: 'rain_mm',
        },
        {
            icon: 'snowflake',
            title: 'Snow mm:',
            key: 'snow_mm',
        },
    ],
};
