export type WeatherIcons =
    | 'blizzard'
    | 'clear'
    | 'cloudRainThunder'
    | 'cloudSleetSnowThunder'
    | 'cloud'
    | 'cloudLow'
    | 'cloudHigh'
    | 'cloudy'
    | 'drizzle'
    | 'fog'
    | 'freezing'
    | 'rain'
    | 'rainSwrsDay'
    | 'rainSwrsNight'
    | 'rainDrop'
    | 'occLightRain'
    // | 'heavyRain'
    // | 'heavyRainSwrsDay'
    // | 'heavyRainSwrsNight'
    | 'sleet'
    | 'sleetSwrsDay'
    | 'sleetSwrsNight'
    | 'occLightSleet'
    // | 'heavySleet'
    // | 'heavySleetSwrsDay'
    // | 'heavySleetSwrsNight'
    | 'snow'
    | 'snowSwrsDay'
    | 'snowSwrsNight'
    | 'occLightSnow'
    // | 'heavySnowSwrsDay'
    // | 'heavySnowSwrsNight'
    | 'mist'
    | 'overcast'
    | 'partCloudRainThunderDay'
    | 'partCloudRainThunderNight'
    | 'partCloudSleetSnowThunderDay'
    | 'partCloudSleetSnowThunderNight'
    | 'partlyCloudyDay'
    | 'partlyCloudyNight'
    | 'sunny'
    | 'temp'
    | 'tempEmpty'
    | 'windGust'
    | 'windy'
    | 'humidity'
    | 'visibility';

export type WeatherIconMapProps = {
    [key in WeatherIcons]: string;
};
