import { WeatherIconMapProps } from './weather.definition';

export const weatherIconMap: WeatherIconMapProps = {
    blizzard: 'wi wi-dust',
    clear: 'wi wi-night-clear',
    cloudRainThunder: 'wi wi-thunderstorm',
    cloudSleetSnowThunder: 'wi wi-storm-showers',
    cloud: 'wi wi-cloud',
    cloudLow: 'wi wi-cloud-down',
    cloudHigh: 'wi wi-cloud-up',
    cloudy: 'wi wi-cloudy',
    fog: 'wi wi-fog',
    drizzle: 'wi wi-showers',
    // freezingDrizzle: 'wi',
    // freezingFog: 'wi wi-smog',
    // freezingRain: 'wi',
    freezing: 'wi wi-snowflake-cold',
    rain: 'wi wi-rain',
    rainSwrsDay: 'wi wi-day-rain',
    rainSwrsNight: 'wi wi-night-alt-rain',
    rainDrop: 'wi wi-raindrop',
    occLightRain: 'wi wi-rain',
    // isoRainSwrsDay: 'wi wi-day-rain',
    // isoRainSwrsNight: 'wi wi-night-alt-rain',
    // modRain: 'wi',
    // modRainSwrsDay: 'wi ',
    // modRainSwrsNight: 'wi',
    // heavyRain: 'wi wi-rain',
    // heavyRainSwrsDay: 'wi wi-day-rain',
    // heavyRainSwrsNight: 'wi wi-night-alt-rain',
    sleet: 'wi wi-sleet',
    sleetSwrsDay: 'wi wi-day-sleet',
    sleetSwrsNight: 'wi wi-night-alt-sleet',
    occLightSleet: 'wi wi-sleet',
    // isoSleetSwrsDay: 'wi wi-day-rain',
    // isoSleetSwrsNight: 'wi wi-night-alt-rain',
    // modSleet: 'wi',
    // modSleetSwrsDay: 'wi',
    // modSleetSwrsNight: 'wi',
    // heavySleet: 'wi wi-sleet',
    // heavySleetSwrsDay: 'wi wi-day-sleet',
    // heavySleetSwrsNight: 'wi wi-night-alt-sleet',
    snow: 'wi wi-snow',
    snowSwrsDay: 'wi wi-day-snow',
    snowSwrsNight: 'wi wi-night-snow',
    occLightSnow: 'wi wi-snow',
    // isoSnowSwrsDay: 'wi wi-day-rain',
    // isoSnowSwrsNight: 'wi wi-night-alt-rain',
    // modSnow: 'wi',
    // modSnowSwrsDay: 'wi',
    // modSnowSwrsNight: 'wi',
    // heavySnow: 'wi wi-snow',
    // heavySnowSwrsDay: 'wi wi-day-snow',
    // heavySnowSwrsNight: 'wi wi-night-snow',
    mist: 'wi wi-day-haze',
    overcast: 'wi wi-day-sunny-overcast',
    partCloudRainThunderDay: 'wi wi-day-thunderstorm',
    partCloudRainThunderNight: 'wi wi-night-alt-thunderstorm',
    partCloudSleetSnowThunderDay: 'wi wi-day-sleet-storm',
    partCloudSleetSnowThunderNight: 'wi wi-night-alt-sleet-storm',
    partlyCloudyDay: 'wi wi-day-cloudy',
    partlyCloudyNight: 'wi wi-night-alt-cloudy wi-night-alt-cloudy',
    sunny: 'wi wi-day-sunny',
    temp: 'wi wi-thermometer',
    tempEmpty: 'wi wi-thermometer-exterior',
    windGust: 'wi wi-cloudy-gusts',
    windy: 'wi wi-cloudy-windy',
    humidity: 'wi wi-humidity',
    visibility: 'wi wi-hurricane wi-rotate-90',
};
